# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nycstop',
            unique_together=set([('stop_id', 'lat', 'lng', 'type')]),
        ),
    ]
