# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0002_auto_20161212_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nycstop',
            unique_together=set([('stop_id', 'lat', 'lng', 'type', 'street')]),
        ),
    ]
